# Generated by Django 5.0.4 on 2024-05-29 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='author_photos')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='art_photos')),
                ('address', models.TextField()),
                ('category', models.CharField(max_length=500)),
                ('measurement', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.author')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
